apiVersion: v1 
kind: ReplicationController 
metadata: 
  name: zhmb1
  namespace: kube-ecos
  labels: 
    name: zhmb1
spec: 
  replicas: 1
  selector: 
    name: zhmb1 
  template: 
    metadata: 
      labels: 
        name: zhmb1 
    spec: 
      volumes: 
      - name: "jdk" 
        hostPath: 
          path: "/public/jdk"
      - name: "data" 
        hostPath: 
          path: "/data/zhmb1"
      containers: 
      - name: zhmb1 
        image: 172.19.80.103:5000/ecos
        ports: 
        - containerPort: 8080
        - containerPort: 8081
        resources:
          limits:
            memory: 2048Mi
        volumeMounts: 
        - name: "jdk" 
          mountPath: "/usr/local/jdk"
        - name: "data" 
          mountPath: "/project"
