apiVersion: v1
kind: Service
metadata: 
  name: zhmb1
  namespace: kube-ecos
  labels: 
    name: zhmb1
spec: 
  type: NodePort
  ports:
  - port: 8080
    nodePort: 9999
  selector: 
    name: zhmb1
