apiVersion: v1
kind: Service
metadata: 
  name: k8smb1
  namespace: kube-system
  labels: 
    name: k8smb1
spec: 
  type: NodePort
  ports:
  - port: 8080
    nodePort: 9999
  selector: 
    name: k8smb1
